runners:
  - name: cirun-gcp-2xl
    cloud: gcp
    instance_type: e2-standard-16
    machine_image: ubuntu-2204-lts
    region: us-central1-a
    preemptible: true
    extra_config:
      baseDisk:
        diskSizeGb: 294
    labels:
      - cirun-gcp-2xl

  - name: cirun-gcp-xlarge
    cloud: gcp
    instance_type: e2-standard-8
    machine_image: ubuntu-2204-lts
    region: us-central1-a
    preemptible: true
    extra_config:
      baseDisk:
        diskSizeGb: 300
    labels:
      - cirun-gcp-xlarge

